WARNING  kubetest:utils.py:139 got api exception while waiting: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '02ca2b74-c00c-4062-85f2-ae2308e81124', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '84aff0d0-903c-4da9-b72b-93ce110ffbc0', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'ad8a96be-1895-4635-a003-5f756d94c58a', 'Date': 'Tue, 08 Oct 2024 16:23:06 GMT', 'Content-Length': '214'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"context-aphrodite\" not found","reason":"NotFound","details":{"name":"context-aphrodite","kind":"namespaces"},"code":404}