WARNING  kubetest:utils.py:139 got api exception while waiting: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'c3bbacea-a1d2-4b91-b3f5-2d434a607739', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'b5f6324a-11cb-499c-97b2-d22accc080a4', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'f364b211-52fc-47a4-9f2e-2d9860ec023e', 'Date': 'Mon, 07 Oct 2024 21:41:34 GMT', 'Content-Length': '214'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"context-aphrodite\" not found","reason":"NotFound","details":{"name":"context-aphrodite","kind":"namespaces"},"code":404}