{"uid":"c9b9485e1659675d","name":"test_cluster","fullName":"test_infra.TestClass#test_cluster","historyId":"4cddaffb932235493819faa85d9a2846","time":{"start":1725967912717,"stop":1725967964308,"duration":51591},"status":"failed","statusMessage":"Failed: Make cluster command failed with return code 2","statusTrace":"self = <test_infra.TestClass object at 0x7d0d7c2ecad0>, cmd = 'make cluster'\n\n    def run_cmd(self, cmd):\n        try:\n>           result = subprocess.run([\"sh\", \"-c\", cmd], check=True, text=True, capture_output=True, cwd=\"../../\")\n\ntest_infra.py:9: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ninput = None, capture_output = True, timeout = None, check = True\npopenargs = (['sh', '-c', 'make cluster'],)\nkwargs = {'cwd': '../../', 'stderr': -1, 'stdout': -1, 'text': True}\nprocess = <Popen: returncode: 2 args: ['sh', '-c', 'make cluster']>\nstdout = \"make[1]: Entering directory '/home/ci/mindwm-gitops'\\nk3s-uninstall.sh ; \\\\\\nsleep 10 # :)\\ndocker version -f json | ...NFO]  systemd: Enabling k3s unit\\n[INFO]  systemd: Starting k3s\\nmake[1]: Leaving directory '/home/ci/mindwm-gitops'\\n\"\nstderr = '/bin/bash: line 1: k3s-uninstall.sh: command not found\\nCreated symlink /etc/systemd/system/multi-user.target.wants/k...s.service.\\n/bin/bash: line 3: /home/ci/.kube/config: Permission denied\\nmake[1]: *** [Makefile:76: cluster] Error 1\\n'\nretcode = 2\n\n    def run(*popenargs,\n            input=None, capture_output=False, timeout=None, check=False, **kwargs):\n        \"\"\"Run command with arguments and return a CompletedProcess instance.\n    \n        The returned instance will have attributes args, returncode, stdout and\n        stderr. By default, stdout and stderr are not captured, and those attributes\n        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them,\n        or pass capture_output=True to capture both.\n    \n        If check is True and the exit code was non-zero, it raises a\n        CalledProcessError. The CalledProcessError object will have the return code\n        in the returncode attribute, and output & stderr attributes if those streams\n        were captured.\n    \n        If timeout is given, and the process takes too long, a TimeoutExpired\n        exception will be raised.\n    \n        There is an optional argument \"input\", allowing you to\n        pass bytes or a string to the subprocess's stdin.  If you use this argument\n        you may not also use the Popen constructor's \"stdin\" argument, as\n        it will be used internally.\n    \n        By default, all communication is in bytes, and therefore any \"input\" should\n        be bytes, and the stdout and stderr will be bytes. If in text mode, any\n        \"input\" should be a string, and stdout and stderr will be strings decoded\n        according to locale encoding, or by \"encoding\" if set. Text mode is\n        triggered by setting any of text, encoding, errors or universal_newlines.\n    \n        The other arguments are the same as for the Popen constructor.\n        \"\"\"\n        if input is not None:\n            if kwargs.get('stdin') is not None:\n                raise ValueError('stdin and input arguments may not both be used.')\n            kwargs['stdin'] = PIPE\n    \n        if capture_output:\n            if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:\n                raise ValueError('stdout and stderr arguments may not be used '\n                                 'with capture_output.')\n            kwargs['stdout'] = PIPE\n            kwargs['stderr'] = PIPE\n    \n        with Popen(*popenargs, **kwargs) as process:\n            try:\n                stdout, stderr = process.communicate(input, timeout=timeout)\n            except TimeoutExpired as exc:\n                process.kill()\n                if _mswindows:\n                    # Windows accumulates the output in a single blocking\n                    # read() call run on child threads, with the timeout\n                    # being done in a join() on those threads.  communicate()\n                    # _after_ kill() is required to collect that and add it\n                    # to the exception.\n                    exc.stdout, exc.stderr = process.communicate()\n                else:\n                    # POSIX _communicate already populated the output so\n                    # far into the TimeoutExpired exception.\n                    process.wait()\n                raise\n            except:  # Including KeyboardInterrupt, communicate handled that.\n                process.kill()\n                # We don't call process.wait() as .__exit__ does that for us.\n                raise\n            retcode = process.poll()\n            if check and retcode:\n>               raise CalledProcessError(retcode, process.args,\n                                         output=stdout, stderr=stderr)\nE               subprocess.CalledProcessError: Command '['sh', '-c', 'make cluster']' returned non-zero exit status 2.\n\n/usr/lib/python3.12/subprocess.py:571: CalledProcessError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_infra.TestClass object at 0x7d0d7c2ecad0>\n\n    def test_cluster(self):\n>       self.run_cmd(\"make cluster\")\n\ntest_infra.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <test_infra.TestClass object at 0x7d0d7c2ecad0>, cmd = 'make cluster'\n\n    def run_cmd(self, cmd):\n        try:\n            result = subprocess.run([\"sh\", \"-c\", cmd], check=True, text=True, capture_output=True, cwd=\"../../\")\n            print(\"Command Output:\", result.stdout)\n            assert result.returncode == 0, f\"Expected return code 0 but got {result.returncode}\"\n        except subprocess.CalledProcessError as e:\n            # If the command fails, capture the error and output\n            print(f\"Error executing '{cmd}': {e}\")\n            print(f\"Error Output: {e.stderr}\")\n>           pytest.fail(f\"Make cluster command failed with return code {e.returncode}\")\nE           Failed: Make cluster command failed with return code 2\n\ntest_infra.py:16: Failed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop_policy","time":{"start":1725967912717,"stop":1725967912717,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"afterStages":[],"labels":[{"name":"tag","value":"e2e"},{"name":"suite","value":"test_infra"},{"name":"subSuite","value":"TestClass"},{"name":"host","value":"localhost"},{"name":"thread","value":"4207-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_infra"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["e2e"]},"source":"c9b9485e1659675d.json","parameterValues":[]}